/*
Pink Vulkan Renderer: Response

Error type.
*/

package pink_vk

Response :: enum {
	OK,
	SDL_VULKAN_LOAD_LIBRARY_FAILED,
	VULKAN_CREATE_INSTANCE_FAILED,
	VULKAN_REQUIRED_EXTENSION_UNSUPPORTED,
	VULKAN_VALIDATION_LAYER_UNSUPPORTED,
	SDL_VULKAN_CREATE_SURFACE_FAILED,
	NO_VULKAN_SUPPORTED_DEVICE,
	VULKAN_NO_SUITABLE_DEVICE,
	VULKAN_CREATE_DEVICE_FAILED,
	VULKAN_CREATE_SWAP_CHAIN_FAILED,
	VULKAN_CREATE_IMAGE_VIEW_FAILED,
	VULKAN_CREATE_SHADER_MODULE_FAILED,
	VULKAN_CREATE_RENDER_PASS_FAILED,
	VULKAN_CREATE_PIPELINE_LAYOUT_FAILED,
	VULKAN_CREATE_GRAPHICS_PIPELINES_FAILED,
	VULKAN_CREATE_FRAMEBUFFER_FAILED,
	VULKAN_CREATE_COMMAND_POOL_FAILED,
	VULKAN_ALLOCATE_COMMAND_BUFFERS_FAILED,
	VULKAN_BEGIN_COMMAND_BUFFER_FAILED,
	VULKAN_END_COMMAND_BUFFER_FAILED,
	VULKAN_CREATE_SEMAPHORE_FAILED,
	VULKAN_CREATE_FENCE_FAILED,
	VULKAN_QUEUE_SUBMIT_FAILED,
	VULKAN_ACQUIRE_NEXT_IMAGE_FAILED,
	VULKAN_CREATE_BUFFER_FAILED,
	VULKAN_NO_SUITABLE_MEMORY_TYPE,
	VULKAN_ALLOCATE_MEMORY_FAILED,
}
